sensorfu/luomu-libpcap

- luomu-libpcap/examples/capture.rs
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
Add safe wrapper for `pcap_set_buffer_size()` PCAP function and add `PcapBuilder::set_buffer_size()` method.
These are used to set the PCAP's internal (ring) buffer size so that in high traffic burst situations we don't drop packets if we can't handle them fast enough.
> Add pcap_set_buffer_size() function with associated method

- luomu-libpcap/src/error.rs
- luomu-libpcap/src/functions.rs
Panicing is bad, but so are undocumented errors from Pcap. Now it's up to user to handle these unknown errors. Its probably better than panicing.
> Remove panics from Pcap error codes we don't recognize

- luomu-libpcap/src/lib.rs
Because PcapT didn't implement Drop, the libpcap's handle pcap_t was not properly closed leading pcap_t handle getting lost. This might lead to memory and/or file handle leaks. This depends on libpcap internals and e.g. operating system.
If you want to dig further into what might have leaked, libpcap's pcap_close is defined in
https://github.com/the-tcpdump-group/libpcap/blob/d615abec7e0237299250c409dca23effb8dd36cc/pcap.c#L3888-L3895
> Drop was not implemented for PcapT leading to resource leak

- luomu-libpcap/examples/capture.rs
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
Adds new struct capsulating the `pcap_stat` structure used by` libpcap`.
Getters are added allowing to read the statistics values without the need
to know the internals.
Also adds a method for `Pcap` which returns ` PcapStat` struct containing the
statistics.
capture example is updated to use the new stats method and prints statistics for every 100 packets received.
> Add method a method for Pcap to read libpcap statistics

- .github/workflows/rust_matrix.yml
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
Improve safety on two places:
1.  Move pcap_close(), pcap_freecode() and pcap_freealldevs() code to Drop
Move the implementation of these function in appropriate Drop trait. Then this function can take the ownership of the struct in question and it's automatically dropped when function ends.
2. Use MaybeUninit to manage uninitialized memory in pcap_compile
We need to allocate memory for libpcap::bpf_program, but allocation leaves it in invalid state. We can wrap bpf_program in MaybeUninit until the contents are initialized by pcap_compile(). After we are sure pcap_compile() compiled the program we take the bpf_program out from MaybeUninit and can be certain it's properly defined.
Fixes #12
> Safety concerns

- luomu-libpcap/examples/capture.rs
- luomu-libpcap/src/lib.rs
Currently the Pcap filter is set with `PcapBuilder`, but it feels quirky because filter must be set after Pcap is activated. This PR removes setting the filter in` PcapBuilder` and now it must be set in `Pcap` struct directly. I also realized there's no need to store the Pcap filter anywhere. It's stated in documentation that the compiled filter can be freed after filter is set.
> Set filter for Pcap directly instead of using the builder

- luomu-libpcap/examples/capture.rs
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
When capture is not in immediate mode and there's buffering going we don't know when the packet arrived. It might have been in buffers for seconds. Capture timestamp should help with this.
> Add capture timestamp into Packet

- luomu-libpcap/src/functions.rs
pcap_inject should return non-negative value on success. Steer error
handling towards negative values. This removes confusing debug trace
logging messages:
```
TRACE luomu_libpcap::functions] check_pcap_error(0xffff95fb0b10, 218) = Unknown error: 218
```
> Fix pcap_inject error handling for positive return values

- luomu-tpacketv3/src/if_packet.rs
- luomu-tpacketv3/src/lib.rs
- luomu-tpacketv3/src/ringbuf.rs
Vlan tags might or might not be present in the payload provided by tpacket API. If the are not in the data, they are provided in PacketDescriptor header and associated flags in the status flags are set. Add support for detecting this and providing the data with methods in `Packet` struct.. 
If the vlan information was provided by Packet Descriptor header and is no longer present in the actual packet payload, it can be read from `Packet` using `vlan_tpid()` and `vlan_tci()` methods.
> Add support for getting vlan tag and control information if it is stripped from packet

- luomu-libpcap/src/functions.rs
Add missing parameter for `PcapT` construction. Was left out due to sloppy rebase.
> Add missing 'interface' parameter

- luomu-libpcap/src/lib.rs
- luomu-libpcap/tests/pcap-interfaces.rs
- luomu-tpacketv3/Cargo.toml
- luomu-tpacketv3/examples/demo.rs
- luomu-tpacketv3/src/lib.rs
- luomu-tpacketv3/src/socket.rs
* Add support for getting the raw compiled filter program from `PcapFilter` while trying to make sure the returned raw filter does not outlive `PcapFilter`
* Add support for attaching bpf filter program to socket using `SO_ATTACH_FILTER` socket option in tpacketv3 wrapper
* Change `tpacketv3::reader()` function to allow specifying pcap filter (with `Option<&str>`) to use.
* This changes tpacketv3 to to require `luomu_libpcap` as build time dependency.
> Add support for filtering packets with "pcap filter" in tpacketv3

- .github/workflows/rust_matrix.yml
- luomu-common/src/address.rs
Fixes clippy warning.
```
warning: match expression looks like `matches!` macro
--> luomu-common/src/address.rs:20:9
|
20 | /         match self {
21 | |             Address::Ipv4(_) => true,
22 | |             _ => false,
23 | |         }
| |_________^ help: try this: `matches!(self, Address::Ipv4(_))`
|
= note: `#[warn(clippy::match_like_matches_macro)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#match_like_matches_macro
```
> Use matches!() macro where applicable

- luomu-libpcap/src/error.rs
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
1. Move generic error check later after happy path is handled
The `pcap_next_ex()` function is called for every packet. And usually packet is received without error or timeout happens. Handle these cases first and check for errors later.
This change avoids calling `check_pcap_error()` for every received packet.
1. Make check_pcap_error() return fast for PCAP_SUCCESS/PCAP_ERROR
These two values don't care about the interface name, and success or error is checked for all the time. Thus handle early and return fast before doing the interface String copying business.
> Small optimizations to error handling

- luomu-libpcap/Cargo.toml
- luomu-libpcap/src/error.rs
- luomu-libpcap/tests/errors.rs
This type wasn't compatible with anyhow crate. This is just band aid to get forward. Proper fix might be to switch to thiserror crate for our Error type.
> Remove Box<dyn Error> from our error type

- luomu-libpcap/Cargo.toml
- luomu-libpcap/examples/tokio-capture.rs
- luomu-libpcap/src/error.rs
- luomu-libpcap/src/lib.rs
- luomu-libpcap/src/tokio.rs
The AsyncCapture implements Future and Stream, and is async framework agnostic.
However, due to how libpcap works and this implementation we rely on libpcap's pcap_next_ex() timeouts and/or packet buffers to return once in a while to let other tasks run.
> Add AsyncCapture for testing how asynchronous pcap could work

- .github/workflows/rust_matrix.yml
- luomu-libpcap/examples/offline.rs
- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
- luomu-tpacketv3/src/lib.rs
Adds `Pcap::offline()` method to start reading packets from file instead of reading live traffic from interface.
> Add support for reading packets from saved pcap file

- luomu-libpcap/Cargo.toml
- luomu-libpcap/src/lib.rs
This allows accessing packet contents as [Bytes](https://docs.rs/bytes/latest/bytes/struct.Bytes.html). It implies copying the packet contents once, but after that Bytes should allow slicing'n'dicing itself without further need for copying.
> Add optional support for bytes crate

- luomu-common/src/addr_pair.rs
- luomu-common/src/directed_addr.rs
- luomu-common/src/lib.rs
Many network protocols have pair of addresses of some kind. Ethernet frames have source and destination MAC addresses, IP has either IPv4 or IPv6 addresses and TCP and UDP protocols have source and destination port numbers. This trait and types supporting it make it simple to have single type containing both addresses and keeping the direction.
> Add trait for address pairs and introduce types required

- luomu-common/src/macaddr.rs
Implement `TryFrom<&str>` and `Display` for MacAddress. Add method to check if address is multicast address.
> Add utility methods for MacAddress

- luomu-libpcap/examples/capture.rs
- luomu-libpcap/src/lib.rs
In my opinion, the iterator should return None in the case of a timeout. With this, the iterator is no longer blocking and a consumer can decide themselves when to stop the loop. This is especially important if one would like to run the capture in a parallel thread and be able to stop that thread gracefully by notfiying it.
To make this more clear, some (pseudo-)code:
```rust
let (s,r) = mspc::channel();
let _ = thread::spawn(move || {
let pcap Pcap::builder("lo").expect("").activate().expect("");
let mut packets = Vec::new();
loop {
match pcap.capture().next() {
None => {}
Some(pkt) => {
packets.push(pkt);
}
};
match r.try_recv() {
Ok(_) | Err(TryRecvError::Disconnected) => {
// save packets to file
break;
},
Err(TryRecvError::Empty) => {},
}
}
}
thread::sleep(Duration::from_secs(10)); …
```
> unblock pcap iterator

- Cargo.toml
- README.md
- luomu-getifaddrs/Cargo.toml
- luomu-getifaddrs/examples/interfaces.rs
- luomu-getifaddrs/examples/ipaddresses.rs
- luomu-getifaddrs/examples/macaddresses.rs
- luomu-getifaddrs/src/flags.rs
- luomu-getifaddrs/src/lib.rs
- luomu-getifaddrs/src/stats.rs
`luomu-getifaddrs` provides wrappers for `getifaddrs()` providing ability to fetch addresses (IP, MAC) and some statistics for interfaces .
While at it, added also some information to main README
> Add crate containing wrapper for getifaddrs()

- luomu-libpcap/src/functions.rs
- luomu-libpcap/src/lib.rs
- luomu-libpcap/src/packet.rs
Boxes are good because they consume less space and we don't need to change the size of these `Strings`/`Vec<u8>`s.
> Convert some String/Vec<u8> into respective Boxes

- .github/workflows/rust_matrix.yml
- Cross.toml
- luomu-libpcap-sys/generate.sh
- luomu-libpcap-sys/src/pcap.rs
These are platform dependent (e.g. 64bit vs 32bit) and didn't compile on 32bit platform.
> Remove layout tests from bindgen generated bindings

- Cargo.toml
- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzz_targets/macaddr-from-str.rs
- luomu-common/src/lib.rs
- luomu-common/src/macaddr.rs
- luomu-common/src/tagged_macaddr.rs
Compiler probably does this anyway. And this way we can have access to upper two bytes if we want to.
> Change MacAddr to hold u64 instead of byte array

- luomu-common/src/ipaddr.rs
- luomu-common/src/macaddr.rs
* Add a function to compute Solicited-Node multicast address for (unicast) IPv6 address.
* Add a function to check if `IPv6Address` is a Solicited-Node multicast address
* Add a method for `MacAddr` to create a `MacAddr` corresponding to multicast address.
> Add some utility functions

- luomu-common/src/addr_pair.rs
- luomu-common/src/directed_addr.rs
The naming of `unwrap()` method for `Source` and `Destination` is a bit unfortunate as `unwrap()` is almost like a reserved word. This leads into confusion in, for example, code reviews where `unwrap()` might be confused with a call which might lead to panic.
Thus, add `into_inner()` which does the same thing as `unwrap()` and is in line with the way this kind of methods are typically named.
Also, deprecate the `unwrap()` allowing us to remove it in the future.
> Add `{Source, Destination}::into_inner()`
